from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import inch
import os
from datetime import datetime


def create_report(report):

    os.makedirs("reports", exist_ok=True)

    report_id = str(report.get("id") or report.get("_id"))

    filename = f"report_{report_id}.pdf"
    path = os.path.join("reports", filename)

    doc = SimpleDocTemplate(
        path,
        rightMargin=35,
        leftMargin=35,
        topMargin=40,
        bottomMargin=35,
    )

    styles = getSampleStyleSheet()

    title = styles["Heading1"]
    title.alignment = TA_CENTER
    title.textColor = colors.HexColor("#2563eb")

    heading = styles["Heading2"]
    heading.textColor = colors.HexColor("#2563eb")

    body = styles["BodyText"]

    story = []

    story.append(Paragraph("<b>MedAssist AI</b>", title))
    story.append(
        Paragraph(
            "Artificial Intelligence Medical Assessment Report",
            heading,
        )
    )

    story.append(Spacer(1, 0.25 * inch))

    table = Table([
        ["Report ID", report_id],
        [
            "Generated On",
            datetime.now().strftime("%d-%m-%Y %I:%M %p"),
        ],
        [
            "Predicted Disease",
            report.get("prediction", "-"),
        ],
        [
            "Confidence",
            f"{report.get('confidence',0)} %",
        ],
        [
            "Risk Level",
            report.get("risk", "-"),
        ],
    ], colWidths=[150, 260])

    table.setStyle(TableStyle([
        ("GRID", (0,0), (-1,-1), 1, colors.grey),
        ("BACKGROUND", (0,0), (0,-1), colors.HexColor("#E8F0FE")),
        ("TEXTCOLOR", (0,0), (-1,-1), colors.black),
        ("FONTNAME", (0,0), (-1,-1), "Helvetica"),
        ("FONTNAME", (0,0), (0,-1), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0,0), (-1,-1), 8),
    ]))

    story.append(table)

    story.append(Spacer(1, 18))

    story.append(Paragraph("Symptoms Reported", heading))

    for symptom in report.get("symptoms", []):
        story.append(Paragraph(f"• {symptom}", body))

    story.append(Spacer(1, 12))

    story.append(Paragraph("AI Diagnosis", heading))

    story.append(
        Paragraph(
            f"<b>Disease:</b> {report.get('prediction','-')}",
            body,
        )
    )

    story.append(
        Paragraph(
            f"<b>Confidence:</b> {report.get('confidence',0)}%",
            body,
        )
    )

    story.append(
        Paragraph(
            f"<b>Risk Level:</b> {report.get('risk','-')}",
            body,
        )
    )

    story.append(Spacer(1, 15))

    story.append(Paragraph("Recommendations", heading))

    recommendations = report.get("recommendations", [])

    for i, rec in enumerate(recommendations, start=1):
        story.append(
            Paragraph(f"{i}. {rec}", body)
        )

    story.append(Spacer(1, 18))

    story.append(Paragraph("Overall Assessment", heading))

    story.append(
        Paragraph(
            f"""
            The patient is predicted to have
            <b>{report.get('prediction')}</b>
            with a confidence of
            <b>{report.get('confidence')}%</b>.
            The assessed risk level is
            <b>{report.get('risk')}</b>.
            """,
            body,
        )
    )

    story.append(Spacer(1, 15))

    story.append(Paragraph("Medical Disclaimer", heading))

    story.append(
        Paragraph(
            "This report is AI-generated and should not replace a professional medical diagnosis. Please consult a qualified healthcare professional before taking any medical decision.",
            body,
        )
    )

    story.append(Spacer(1, 20))

    footer = styles["Italic"]
    footer.alignment = TA_CENTER
    footer.textColor = colors.grey

    story.append(
        Paragraph(
            "Generated by MedAssist AI • Confidential Medical Report",
            footer,
        )
    )

    doc.build(story)

    return path