export const Role = {
  SUPER_ADMIN: "SUPER_ADMIN",
  HOSPITAL_ADMIN: "HOSPITAL_ADMIN",
  DOCTOR: "DOCTOR",
  PHARMACY: "PHARMACY",
  PATIENT: "PATIENT",

  // Legacy aliases for route compatibility
  ADMIN: "SUPER_ADMIN",
  CLINIC: "PHARMACY",
  APPOINTMENT: "APPOINTMENT",
};
